<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-T0CQONB0" failures="2" tests="13" name="Default test" time="6.363" errors="0" timestamp="2025-02-23T02:04:16 SGT">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="2.3"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.396"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="1.179"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.381"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.398">
    <failure type="java.lang.AssertionError" message="Status code does not match
Expected: &amp;lt;400&amp;gt;
     but: was &amp;lt;200&amp;gt;">
      <![CDATA[java.lang.AssertionError: Status code does not match
Expected: <400>
     but: was <200>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at stepDefinitions.BookStepDefinitions.verify_status_code(BookStepDefinitions.java:75)
at ✽.the status code is 400(file:///C:/Users/NISHTHA%20MISHRA/OneDrive/Desktop/ETL_Automation_Data/src/test/java/cucumber_maven/featurestest/ApiResponse.feature:44)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.914"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.032">
    <failure type="java.lang.AssertionError" message="Duplicate PatientID found: P001">
      <![CDATA[java.lang.AssertionError: Duplicate PatientID found: P001
at org.junit.Assert.fail(Assert.java:89)
at stepDefinitions.Datavalidationsteps.i_should_see_no_duplicate_patient_ids(Datavalidationsteps.java:111)
at ✽.I should see no duplicate PatientIDs(file:///C:/Users/NISHTHA%20MISHRA/OneDrive/Desktop/ETL_Automation_Data/src/test/java/cucumber_maven/featurestest/MergeClaims.feature:12)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.035"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.032"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.027"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.033"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.028"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.027"/>
</testsuite> <!-- Default test -->
